version: 2
jobs:
  "node-11":
    docker:
      - image: circleci/node:11
    working_directory: ~/back-off
    steps:
      - checkout

      - run: npm install
      - run: npm run lint
      # run tests!
      - run: npm test
      - run: npm run coverage

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/back-off
    steps:
      - checkout

      - run: npm install
      - run: npm test

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/back-off
    steps:
      - checkout

      - run: npm install
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-11"
      - "node-10"
      - "node-8"